name: dbt_carton_caps
version: "1.0"
config-version: 2

profile: dbt_carton_caps

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

models:
  dbt_carton_caps:
    +materialized: view
    staging:
      +materialized: view
    marts:
      +materialized: table
